# Generated by Django 6.0.5 on 2026-06-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchEvent',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=15)),
            ],
        ),
    ]
