# Generated by Django 6.0.5 on 2026-06-02 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Livestream',
            fields=[
                ('event_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('started', models.DateTimeField()),
                ('ended', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.channel')),
            ],
        ),
    ]
