# Generated by Django 6.0.5 on 2026-06-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='title',
            field=models.CharField(default='N/A', max_length=500),
            preserve_default=False,
        ),
    ]
