# Generated by Django 6.0.5 on 2026-06-10 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0002_livestream_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livestream',
            old_name='user_id',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='livestream',
            old_name='event_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='channel',
            name='offline_event_id',
            field=models.CharField(default='ERROR', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='online_event_id',
            field=models.CharField(default='ERROR', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='update_event_id',
            field=models.CharField(default='ERROR', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livestream',
            name='ended',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='LivestreamCategory',
            fields=[
                ('livestream_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Common.livestream')),
                ('category', models.CharField(max_length=100)),
                ('changed_at', models.DateTimeField()),
            ],
            options={
                'unique_together': {('livestream_id', 'category')},
            },
        ),
    ]
