# Generated by Django 6.0.5 on 2026-06-10 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0003_rename_user_id_livestream_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestreamcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='livestreamcategory',
            name='livestream_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.livestream'),
        ),
    ]
