# Generated by Django 6.0.5 on 2026-06-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0004_livestreamcategory_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='livestreamcategory',
            unique_together=set(),
        ),
    ]
